/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Antonio Guzzo
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListarPalabras = new javax.swing.JButton();
        MostrarInvestigaciones = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        InputBuscador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Investigaciones = new javax.swing.JComboBox<>();
        BuscarPorPalabra = new javax.swing.JButton();
        CargarArchivo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PantallaResultado = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        SelectAutores = new javax.swing.JComboBox<>();
        BuscarPorAutor = new javax.swing.JButton();
        ListaInvestigaciones = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        Analizar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("SuperMetroMendeley");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel2.setText("Listar palabras claves:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        ListarPalabras.setText("Listar");
        ListarPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPalabrasActionPerformed(evt);
            }
        });
        jPanel1.add(ListarPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        MostrarInvestigaciones.setText("Mostrar investigaciones");
        MostrarInvestigaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarInvestigacionesActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarInvestigaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jLabel3.setText("Resultado - Analisis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));
        jPanel1.add(InputBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, -1));

        jLabel4.setText("Buscar Investigaciones por palabra clave: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        Investigaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(Investigaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 110, -1));

        BuscarPorPalabra.setText("Buscar");
        BuscarPorPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorPalabraActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarPorPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        CargarArchivo.setText("Cargar archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel5.setText("Buscar Investigaciones por Autor:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        PantallaResultado.setColumns(20);
        PantallaResultado.setRows(5);
        jScrollPane1.setViewportView(PantallaResultado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 410, 290));

        jLabel6.setText("Antonio Guzzo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        SelectAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(SelectAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, -1));

        BuscarPorAutor.setText("Buscar");
        BuscarPorAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorAutorActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarPorAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        ListaInvestigaciones.setViewportView(jTextArea2);

        jPanel1.add(ListaInvestigaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 340, 110));

        jLabel7.setText("Agregar archivo informacion inicial");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 56, -1, -1));

        Analizar1.setText("Analizar");
        Analizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Analizar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Analizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListarPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPalabrasActionPerformed
        //
    }//GEN-LAST:event_ListarPalabrasActionPerformed

    private void MostrarInvestigacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarInvestigacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarInvestigacionesActionPerformed

    private void BuscarPorPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorPalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarPorPalabraActionPerformed

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        // Se crea el Objeto JFileChooser
        JFileChooser fc = new JFileChooser();

        // Se crea el filtro para que solo se acepte TXT
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");

        // Se le indica el filtro
        fc.setFileFilter(filtro);

        // Se abre la ventana, y se guarda la op seleccionada por el usuario
        int seleccion = fc.showOpenDialog(this);
        
        // Si el usuario presiona aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Selecciono el fichero
            File fichero = fc.getSelectedFile();

            try (FileReader fr = new FileReader(fichero); BufferedReader br = new BufferedReader(fr)) {
                String linea;
                String titulo = "";
                String autores = "";
                String resumen = "";
                String palabrasClave = "";

                while ((linea = br.readLine()) != null) {
                    linea = linea.trim();
                    if (linea.isEmpty()) continue;

                    if (linea.startsWith("Titulo:")) {
                        titulo = linea.substring(7).trim();
                    } else if (linea.startsWith("Autores:")) {
                        autores = linea.substring(8).trim();
                    } else if (linea.startsWith("Resumen:")) {
                        resumen = linea.substring(8).trim();
                    } else if (linea.startsWith("Palabras claves:") || linea.startsWith("Palabras Claves:")) {
                        palabrasClave = linea.substring(linea.indexOf(":") + 1).trim();

                        System.out.println("Título: " + titulo);
                        System.out.println("Autores: " + autores);
                        System.out.println("Resumen: " + resumen);
                        System.out.println("Palabras Claves: " + palabrasClave);
                        System.out.println("-----------------------------------");

                        // Reinicia para el siguiente bloque
                        titulo = "";
                        autores = "";
                        resumen = "";
                        palabrasClave = "";
                    }
                }
            } catch (IOException e1) {
                e1.printStackTrace();
            }
        } else {
            // Muestra un mensaje de error si no se ha escogido un archivo válido.
            JOptionPane.showMessageDialog(null, "No se escogió un archivo válido");
        }
        JOptionPane.showMessageDialog(null, "Informacion cargada");
    }//GEN-LAST:event_CargarArchivoActionPerformed

    private void BuscarPorAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarPorAutorActionPerformed

    private void Analizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Analizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Analizar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analizar1;
    private javax.swing.JButton BuscarPorAutor;
    private javax.swing.JButton BuscarPorPalabra;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JTextField InputBuscador;
    private javax.swing.JComboBox<String> Investigaciones;
    private javax.swing.JScrollPane ListaInvestigaciones;
    private javax.swing.JButton ListarPalabras;
    private javax.swing.JButton MostrarInvestigaciones;
    private javax.swing.JTextArea PantallaResultado;
    private javax.swing.JComboBox<String> SelectAutores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
